FROM node:10-alpine AS builder

WORKDIR /build
COPY package*.json .babelrc /build/
COPY app /build/app/
RUN ls && npm install && npm run _build

FROM node:10-alpine
ENV HOME=/home/app
WORKDIR ${HOME}

COPY config ${HOME}/config/
COPY package*.json ${HOME}/
COPY --from=builder /build/dist ${HOME}/dist
RUN npm install --production

EXPOSE 3000

CMD npm run _production:run
